# Generated by Django 3.2.8 on 2021-10-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
