name: Rafael Meireles

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      DATABASE_URL: postgres://pythonpro:pythonpro@localhost:5432/cursodjango
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pythonpro
          POSTGRES_PASSWORD: pythonpro
          POSTGRES_DB: cursodjango
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Copiar Configurações .env
        run: |
          cp contrib/env-sample .env
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install codecov
          pip install -r requirements-dev.txt
      - name: Lint com flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Teste de código com pytest
        run: |
          pytest --cov=pypro
      - name: Cobertura de testes com codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
